{"totalCount":7,"grade":"D","repositories":[{"url":"https://github.com/MTES-MCT/carbure","vulnerabilityAlerts":{"totalCount":7,"nodes":[{"dismissedAt":null,"createdAt":"2025-09-09T22:02:19Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-6w2r-r2m5-xq5w"},{"type":"CVE","value":"CVE-2025-57833"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2025-57833"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/g/django-announce"},{"url":"https://medium.com/@EyalSec/django-unauthenticated-0-click-rce-and-sql-injection-using-default-configuration-059964f3f898"},{"url":"https://www.djangoproject.com/weblog/2025/sep/03/security-releases"},{"url":"https://github.com/django/django/commit/102965ea93072fe3c39a30be437c683ec1106ef5"},{"url":"https://github.com/django/django/commit/31334e6965ad136a5e369993b01721499c5d1a92"},{"url":"https://github.com/django/django/commit/4c044fcc866ec226f612c475950b690b0139d243"},{"url":"https://github.com/advisories/GHSA-6w2r-r2m5-xq5w"}]}}},{"dismissedAt":null,"createdAt":"2025-09-10T09:34:04Z","securityVulnerability":{"severity":"LOW","package":{"name":"vite"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-jqfw-vq24-v9c3"},{"type":"CVE","value":"CVE-2025-58752"}],"references":[{"url":"https://github.com/vitejs/vite/security/advisories/GHSA-jqfw-vq24-v9c3"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2025-58752"},{"url":"https://github.com/vitejs/vite/commit/0ab19ea9fcb66f544328f442cf6e70f7c0528d5f"},{"url":"https://github.com/vitejs/vite/commit/14015d794f69accba68798bd0e15135bc51c9c1e"},{"url":"https://github.com/vitejs/vite/commit/482000f57f56fe6ff2e905305100cfe03043ddea"},{"url":"https://github.com/vitejs/vite/commit/6f01ff4fe072bcfcd4e2a84811772b818cd51fe6"},{"url":"https://github.com/vitejs/vite/blob/v7.1.5/packages/vite/CHANGELOG.md"},{"url":"https://github.com/advisories/GHSA-jqfw-vq24-v9c3"}]}}},{"dismissedAt":null,"createdAt":"2025-09-10T09:34:04Z","securityVulnerability":{"severity":"LOW","package":{"name":"vite"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-g4jq-h2w9-997c"},{"type":"CVE","value":"CVE-2025-58751"}],"references":[{"url":"https://github.com/vitejs/vite/security/advisories/GHSA-g4jq-h2w9-997c"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2025-58751"},{"url":"https://github.com/lukeed/sirv/commit/f0113f3f8266328d804ee808f763a3c11f8997eb"},{"url":"https://github.com/vitejs/vite/commit/09f2b52e8d5907f26602653caf41b3a56692600d"},{"url":"https://github.com/vitejs/vite/commit/4f1c35bcbb5830290c694aa14b6789e07450f069"},{"url":"https://github.com/vitejs/vite/commit/63e2a5d232218f3f8d852056751e609a5367aaec"},{"url":"https://github.com/vitejs/vite/commit/e11d24008b97d4ca731ecc1a3b95260a6d12e7e0"},{"url":"https://github.com/advisories/GHSA-g4jq-h2w9-997c"}]}}},{"dismissedAt":null,"createdAt":"2025-09-30T10:03:54Z","securityVulnerability":{"severity":"HIGH","package":{"name":"axios"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-4hjh-wcwx-xvwj"},{"type":"CVE","value":"CVE-2025-58754"}],"references":[{"url":"https://github.com/axios/axios/security/advisories/GHSA-4hjh-wcwx-xvwj"},{"url":"https://github.com/axios/axios/pull/7011"},{"url":"https://github.com/axios/axios/commit/945435fc51467303768202250debb8d4ae892593"},{"url":"https://github.com/axios/axios/releases/tag/v1.12.0"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2025-58754"},{"url":"https://github.com/axios/axios/pull/7034"},{"url":"https://github.com/axios/axios/commit/a1b1d3f073a988601583a604f5f9f5d05a3d0b67"},{"url":"https://github.com/axios/axios/releases/tag/v0.30.2"},{"url":"https://github.com/advisories/GHSA-4hjh-wcwx-xvwj"}]}}},{"dismissedAt":null,"createdAt":"2025-09-30T17:48:51Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"pip"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-4xh5-x5gv-qwph"},{"type":"CVE","value":"CVE-2025-8869"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2025-8869"},{"url":"https://github.com/pypa/pip/pull/13550"},{"url":"https://mail.python.org/archives/list/security-announce@python.org/thread/IF5A3GCJY3VH7BVHJKOWOJFKTW7VFQEN"},{"url":"https://github.com/pypa/pip/commit/f2b92314da012b9fffa36b3f3e67748a37ef464a"},{"url":"https://pip.pypa.io/en/stable/news/#v25-2"},{"url":"https://github.com/advisories/GHSA-4xh5-x5gv-qwph"}]}}},{"dismissedAt":null,"createdAt":"2025-10-01T22:06:28Z","securityVulnerability":{"severity":"LOW","package":{"name":"django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-q95w-c7qg-hrff"},{"type":"CVE","value":"CVE-2025-59682"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2025-59682"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/g/django-announce"},{"url":"https://www.djangoproject.com/weblog/2025/oct/01/security-releases"},{"url":"https://github.com/django/django/commit/43d84aef04a9e71164c21a74885996981857e66e"},{"url":"https://github.com/django/django/commit/924a0c092e65fa2d0953fd1855d2dc8786d94de2"},{"url":"https://github.com/advisories/GHSA-q95w-c7qg-hrff"}]}}},{"dismissedAt":null,"createdAt":"2025-10-01T22:07:48Z","securityVulnerability":{"severity":"HIGH","package":{"name":"django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-hpr9-3m2g-3j9p"},{"type":"CVE","value":"CVE-2025-59681"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2025-59681"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/g/django-announce"},{"url":"https://www.djangoproject.com/weblog/2025/oct/01/security-releases"},{"url":"https://github.com/django/django/commit/41b43c74bda19753c757036673ea9db74acf494a"},{"url":"https://github.com/django/django/commit/43d84aef04a9e71164c21a74885996981857e66e"},{"url":"https://github.com/advisories/GHSA-hpr9-3m2g-3j9p"}]}}}]},"grade":"D"}]}