{"totalCount":28,"grade":"E","repositories":[{"url":"https://github.com/MTES-MCT/sparte","vulnerabilityAlerts":{"totalCount":28,"nodes":[{"dismissedAt":null,"createdAt":"2023-08-29T23:52:40Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"jupyter-server"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-64x5-55rw-9974"},{"type":"CVE","value":"CVE-2023-40170"}],"references":[{"url":"https://github.com/jupyter-server/jupyter_server/security/advisories/GHSA-64x5-55rw-9974"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-40170"},{"url":"https://github.com/jupyter-server/jupyter_server/commit/87a4927272819f0b1cae1afa4c8c86ee2da002fd"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/jupyter-server/PYSEC-2023-157.yaml"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XDKQAWQN6SQTOVACZNXYKEHWQXGG4DOF/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NRP7DNZYVOIA4ZB3U3ZWKTFZEPYWNGCQ/"},{"url":"https://github.com/advisories/GHSA-64x5-55rw-9974"}]}}},{"dismissedAt":null,"createdAt":"2023-08-29T23:52:47Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"jupyter-server"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-r726-vmfq-j9j3"},{"type":"CVE","value":"CVE-2023-39968"}],"references":[{"url":"https://github.com/jupyter-server/jupyter_server/security/advisories/GHSA-r726-vmfq-j9j3"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-39968"},{"url":"https://github.com/jupyter-server/jupyter_server/commit/290362593b2ffb23c59f8114d76f77875de4b925"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/jupyter-server/PYSEC-2023-155.yaml"},{"url":"https://blog.xss.am/2023/08/cve-2023-39968-jupyter-token-leak"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NRP7DNZYVOIA4ZB3U3ZWKTFZEPYWNGCQ"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XDKQAWQN6SQTOVACZNXYKEHWQXGG4DOF"},{"url":"https://github.com/advisories/GHSA-r726-vmfq-j9j3"}]}}},{"dismissedAt":null,"createdAt":"2023-12-05T18:26:07Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"jupyter-server"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-h56g-gq9v-vc8r"},{"type":"CVE","value":"CVE-2023-49080"}],"references":[{"url":"https://github.com/jupyter-server/jupyter_server/security/advisories/GHSA-h56g-gq9v-vc8r"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-49080"},{"url":"https://github.com/jupyter-server/jupyter_server/commit/0056c3aa52cbb28b263a7a609ae5f17618b36652"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/jupyter-server/PYSEC-2023-272.yaml"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/62LO7PPIAMLIDEKUOORXLHKLGA6QPL77"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FG2JWZI5KPUYMDPS53AIFTZJWZD3IT6I"},{"url":"https://github.com/advisories/GHSA-h56g-gq9v-vc8r"}]}}},{"dismissedAt":null,"createdAt":"2024-07-10T22:00:49Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-qg2p-9jwr-mmqf"},{"type":"CVE","value":"CVE-2024-38875"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-38875"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/7285644640f085f41d60ab0c8ae4e9153f0485db"},{"url":"https://github.com/django/django/commit/79f368764295df109a37192f6182fb6f361d85b5"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-56.yaml"},{"url":"https://github.com/advisories/GHSA-qg2p-9jwr-mmqf"}]}}},{"dismissedAt":null,"createdAt":"2024-07-10T22:01:31Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-9jmf-237g-qf46"},{"type":"CVE","value":"CVE-2024-39330"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39330"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/2b00edc0151a660d1eb86da4059904a0fc4e095e"},{"url":"https://github.com/django/django/commit/9f4f63e9ebb7bf6cb9547ee4e2526b9b96703270"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-58.yaml"},{"url":"https://github.com/advisories/GHSA-9jmf-237g-qf46"}]}}},{"dismissedAt":null,"createdAt":"2024-07-10T22:01:45Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-x7q2-wr7g-xqmf"},{"type":"CVE","value":"CVE-2024-39329"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39329"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/07cefdee4a9d1fcd9a3a631cbd07c78defd1923b"},{"url":"https://github.com/django/django/commit/156d3186c96e3ec2ca73b8b25dc2ef366e38df14"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-57.yaml"},{"url":"https://github.com/advisories/GHSA-x7q2-wr7g-xqmf"}]}}},{"dismissedAt":null,"createdAt":"2024-07-10T22:03:00Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-f6f8-9mx6-9mx2"},{"type":"CVE","value":"CVE-2024-39614"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39614"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/17358fb35fb7217423d4c4877ccb6d1a3a40b1c3"},{"url":"https://github.com/django/django/commit/8e7a44e4bec0f11474699c3111a5e0a45afe7f49"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-59.yaml"},{"url":"https://github.com/advisories/GHSA-f6f8-9mx6-9mx2"}]}}},{"dismissedAt":null,"createdAt":"2024-07-15T14:14:57Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"axios"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-wf5p-g6vw-rhxx"},{"type":"CVE","value":"CVE-2023-45857"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-45857"},{"url":"https://github.com/axios/axios/issues/6006"},{"url":"https://github.com/axios/axios/issues/6022"},{"url":"https://github.com/axios/axios/pull/6028"},{"url":"https://github.com/axios/axios/commit/96ee232bd3ee4de2e657333d4d2191cd389e14d0"},{"url":"https://github.com/axios/axios/releases/tag/v1.6.0"},{"url":"https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459"},{"url":"https://github.com/axios/axios/pull/6091"},{"url":"https://github.com/axios/axios/commit/2755df562b9c194fba6d8b609a383443f6a6e967"},{"url":"https://github.com/axios/axios/releases/tag/v0.28.0"},{"url":"https://security.netapp.com/advisory/ntap-20240621-0006"},{"url":"https://github.com/advisories/GHSA-wf5p-g6vw-rhxx"}]}}},{"dismissedAt":null,"createdAt":"2024-08-07T19:20:47Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-jh75-99hh-qvx9"},{"type":"CVE","value":"CVE-2024-41989"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-41989"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://www.djangoproject.com/weblog/2024/aug/06/security-releases"},{"url":"https://github.com/django/django/commit/27900fe56f3d3cabb4aeb6ccb82f92bab29073a8"},{"url":"https://github.com/django/django/commit/fc76660f589ac07e45e9cd34ccb8087aeb11904b"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-67.yaml"},{"url":"https://github.com/advisories/GHSA-jh75-99hh-qvx9"}]}}},{"dismissedAt":null,"createdAt":"2024-08-07T19:21:02Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-795c-9xpc-xw6g"},{"type":"CVE","value":"CVE-2024-41990"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-41990"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://www.djangoproject.com/weblog/2024/aug/06/security-releases"},{"url":"https://github.com/django/django/commit/7b7b909579c8311c140c89b8a9431bf537febf93"},{"url":"https://github.com/django/django/commit/d0a82e26a74940bf0c78204933c3bdd6a283eb88"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-68.yaml"},{"url":"https://github.com/advisories/GHSA-795c-9xpc-xw6g"}]}}},{"dismissedAt":"2024-10-31T22:14:25Z","createdAt":"2024-08-07T19:21:36Z","securityVulnerability":{"severity":"CRITICAL","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-pv4p-cwwg-4rph"},{"type":"CVE","value":"CVE-2024-42005"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-42005"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://www.djangoproject.com/weblog/2024/aug/06/security-releases"},{"url":"https://github.com/django/django/commit/32ebcbf2e1fe3e5ba79a6554a167efce81f7422d"},{"url":"https://github.com/django/django/commit/f4af67b9b41e0f4c117a8741da3abbd1c869ab28"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-70.yaml"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://github.com/advisories/GHSA-pv4p-cwwg-4rph"}]}}},{"dismissedAt":null,"createdAt":"2024-08-07T19:21:43Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-r836-hh6v-rg5g"},{"type":"CVE","value":"CVE-2024-41991"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-41991"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/aug/06/security-releases"},{"url":"https://github.com/django/django/commit/523da8771bce321023f490f70d71a9e973ddc927"},{"url":"https://github.com/django/django/commit/efea1ef7e2190e3f77ca0651b5458297bc0f6a9f"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-69.yaml"},{"url":"https://github.com/advisories/GHSA-r836-hh6v-rg5g"}]}}},{"dismissedAt":null,"createdAt":"2024-09-04T00:30:04Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"cryptography"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-h4gh-qq45-vh27"}],"references":[{"url":"https://github.com/pyca/cryptography/security/advisories/GHSA-h4gh-qq45-vh27"},{"url":"https://openssl-library.org/news/secadv/20240903.txt"},{"url":"https://github.com/advisories/GHSA-h4gh-qq45-vh27"}]}}},{"dismissedAt":null,"createdAt":"2024-09-11T20:46:24Z","securityVulnerability":{"severity":"LOW","package":{"name":"serve-static"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-cm22-4g7w-348p"},{"type":"CVE","value":"CVE-2024-43800"}],"references":[{"url":"https://github.com/expressjs/serve-static/security/advisories/GHSA-cm22-4g7w-348p"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-43800"},{"url":"https://github.com/expressjs/serve-static/commit/0c11fad159898cdc69fd9ab63269b72468ecaf6b"},{"url":"https://github.com/expressjs/serve-static/commit/ce730896fddce1588111d9ef6fdf20896de5c6fa"},{"url":"https://github.com/advisories/GHSA-cm22-4g7w-348p"}]}}},{"dismissedAt":null,"createdAt":"2024-09-11T21:05:00Z","securityVulnerability":{"severity":"LOW","package":{"name":"send"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-m6fv-jmcg-4jfg"},{"type":"CVE","value":"CVE-2024-43799"}],"references":[{"url":"https://github.com/pillarjs/send/security/advisories/GHSA-m6fv-jmcg-4jfg"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-43799"},{"url":"https://github.com/pillarjs/send/commit/ae4f2989491b392ae2ef3b0015a019770ae65d35"},{"url":"https://github.com/advisories/GHSA-m6fv-jmcg-4jfg"}]}}},{"dismissedAt":null,"createdAt":"2024-10-08T21:25:50Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-5hgc-2vfp-mqvc"},{"type":"CVE","value":"CVE-2024-45230"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-45230"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/sep/03/security-releases"},{"url":"https://github.com/django/django/commit/022ab0a75c76ab2ea31dfcc5f2cf5501e378d397"},{"url":"https://github.com/django/django/commit/813de2672bd7361e9a453ab62cd6e52f96b6525b"},{"url":"https://github.com/django/django/commit/d147a8ebbdf28c17cafbbe2884f0bc57e2bf82e2"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-102.yaml"},{"url":"https://github.com/advisories/GHSA-5hgc-2vfp-mqvc"}]}}},{"dismissedAt":null,"createdAt":"2024-10-09T04:07:16Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-rrqc-c2jx-6jgv"},{"type":"CVE","value":"CVE-2024-45231"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-45231"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/sep/03/security-releases"},{"url":"https://github.com/django/django/commit/3c733c78d6f8e50296d6e248968b6516c92a53ca"},{"url":"https://github.com/django/django/commit/96d84047715ea1715b4bd1594e46122b8a77b9e2"},{"url":"https://github.com/django/django/commit/bf4888d317ba4506d091eeac6e8b4f1fcc731199"},{"url":"https://github.com/advisories/GHSA-rrqc-c2jx-6jgv"}]}}},{"dismissedAt":null,"createdAt":"2024-11-22T22:14:24Z","securityVulnerability":{"severity":"HIGH","package":{"name":"tornado"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-8w49-h785-mj3c"},{"type":"CVE","value":"CVE-2024-52804"}],"references":[{"url":"https://github.com/tornadoweb/tornado/security/advisories/GHSA-8w49-h785-mj3c"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-52804"},{"url":"https://github.com/tornadoweb/tornado/commit/d5ba4a1695fbf7c6a3e54313262639b198291533"},{"url":"https://github.com/advisories/GHSA-8w49-h785-mj3c"}]}}},{"dismissedAt":null,"createdAt":"2024-12-06T18:49:13Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-m9g8-fxxm-xg86"},{"type":"CVE","value":"CVE-2024-53908"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-53908"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/g/django-announce"},{"url":"https://www.openwall.com/lists/oss-security/2024/12/04/3"},{"url":"https://www.djangoproject.com/weblog/2024/dec/04/security-releases"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-157.yaml"},{"url":"https://github.com/advisories/GHSA-m9g8-fxxm-xg86"}]}}},{"dismissedAt":null,"createdAt":"2024-12-06T18:49:30Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-8498-2h75-472j"},{"type":"CVE","value":"CVE-2024-53907"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-53907"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/g/django-announce"},{"url":"https://www.openwall.com/lists/oss-security/2024/12/04/3"},{"url":"https://www.djangoproject.com/weblog/2024/dec/04/security-releases"},{"url":"https://lists.debian.org/debian-lts-announce/2024/12/msg00028.html"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-156.yaml"},{"url":"https://github.com/advisories/GHSA-8498-2h75-472j"}]}}}]},"grade":"E"}]}