{"totalCount":10,"grade":"D","repositories":[{"url":"https://github.com/MTES-MCT/sparte","vulnerabilityAlerts":{"totalCount":10,"nodes":[{"dismissedAt":"2025-03-06T12:35:49Z","createdAt":"2023-08-29T23:52:40Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"jupyter-server"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-64x5-55rw-9974"},{"type":"CVE","value":"CVE-2023-40170"}],"references":[{"url":"https://github.com/jupyter-server/jupyter_server/security/advisories/GHSA-64x5-55rw-9974"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-40170"},{"url":"https://github.com/jupyter-server/jupyter_server/commit/87a4927272819f0b1cae1afa4c8c86ee2da002fd"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/jupyter-server/PYSEC-2023-157.yaml"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XDKQAWQN6SQTOVACZNXYKEHWQXGG4DOF/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NRP7DNZYVOIA4ZB3U3ZWKTFZEPYWNGCQ/"},{"url":"https://github.com/advisories/GHSA-64x5-55rw-9974"}]}}},{"dismissedAt":"2025-03-06T12:35:33Z","createdAt":"2023-08-29T23:52:47Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"jupyter-server"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-r726-vmfq-j9j3"},{"type":"CVE","value":"CVE-2023-39968"}],"references":[{"url":"https://github.com/jupyter-server/jupyter_server/security/advisories/GHSA-r726-vmfq-j9j3"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-39968"},{"url":"https://github.com/jupyter-server/jupyter_server/commit/290362593b2ffb23c59f8114d76f77875de4b925"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/jupyter-server/PYSEC-2023-155.yaml"},{"url":"https://blog.xss.am/2023/08/cve-2023-39968-jupyter-token-leak"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NRP7DNZYVOIA4ZB3U3ZWKTFZEPYWNGCQ"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XDKQAWQN6SQTOVACZNXYKEHWQXGG4DOF"},{"url":"https://github.com/advisories/GHSA-r726-vmfq-j9j3"}]}}},{"dismissedAt":"2025-03-06T12:39:32Z","createdAt":"2023-12-05T18:26:07Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"jupyter-server"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-h56g-gq9v-vc8r"},{"type":"CVE","value":"CVE-2023-49080"}],"references":[{"url":"https://github.com/jupyter-server/jupyter_server/security/advisories/GHSA-h56g-gq9v-vc8r"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-49080"},{"url":"https://github.com/jupyter-server/jupyter_server/commit/0056c3aa52cbb28b263a7a609ae5f17618b36652"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/jupyter-server/PYSEC-2023-272.yaml"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/62LO7PPIAMLIDEKUOORXLHKLGA6QPL77"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FG2JWZI5KPUYMDPS53AIFTZJWZD3IT6I"},{"url":"https://github.com/advisories/GHSA-h56g-gq9v-vc8r"}]}}},{"dismissedAt":"2025-03-06T12:40:03Z","createdAt":"2025-01-13T17:52:52Z","securityVulnerability":{"severity":"HIGH","package":{"name":"virtualenv"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-rqc4-2hc7-8c8v"},{"type":"CVE","value":"CVE-2024-53899"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-53899"},{"url":"https://github.com/pypa/virtualenv/issues/2768"},{"url":"https://github.com/pypa/virtualenv/pull/2771"},{"url":"https://github.com/pypa/virtualenv/releases/tag/20.26.6"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/virtualenv/PYSEC-2024-187.yaml"},{"url":"https://github.com/advisories/GHSA-rqc4-2hc7-8c8v"}]}}},{"dismissedAt":null,"createdAt":"2025-04-29T01:50:07Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"http-proxy-middleware"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-4www-5p9h-95mh"},{"type":"CVE","value":"CVE-2025-32996"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2025-32996"},{"url":"https://github.com/chimurai/http-proxy-middleware/pull/1089"},{"url":"https://github.com/chimurai/http-proxy-middleware/commit/020976044d113fc0bcbbaf995e91d05e2829a145"},{"url":"https://github.com/chimurai/http-proxy-middleware/releases/tag/v2.0.8"},{"url":"https://github.com/chimurai/http-proxy-middleware/releases/tag/v3.0.4"},{"url":"https://github.com/advisories/GHSA-4www-5p9h-95mh"}]}}},{"dismissedAt":null,"createdAt":"2025-05-08T15:37:02Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-8j24-cjrq-gr2m"},{"type":"CVE","value":"CVE-2025-32873"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2025-32873"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/g/django-announce"},{"url":"https://www.djangoproject.com/weblog/2025/may/07/security-releases"},{"url":"http://www.openwall.com/lists/oss-security/2025/05/07/1"},{"url":"https://github.com/django/django/commit/9f3419b519799d69f2aba70b9d25abe2e70d03e0"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2025-37.yaml"},{"url":"https://github.com/advisories/GHSA-8j24-cjrq-gr2m"}]}}},{"dismissedAt":null,"createdAt":"2025-05-19T13:33:40Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"@babel/helpers"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-968p-4wvh-cqc8"},{"type":"CVE","value":"CVE-2025-27789"}],"references":[{"url":"https://github.com/babel/babel/security/advisories/GHSA-968p-4wvh-cqc8"},{"url":"https://github.com/babel/babel/pull/17173"},{"url":"https://github.com/babel/babel/commit/d5952e80c0faa5ec20e35085531b6e572d31dad4"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2025-27789"},{"url":"https://github.com/advisories/GHSA-968p-4wvh-cqc8"}]}}},{"dismissedAt":null,"createdAt":"2025-05-19T13:33:40Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"@babel/runtime"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-968p-4wvh-cqc8"},{"type":"CVE","value":"CVE-2025-27789"}],"references":[{"url":"https://github.com/babel/babel/security/advisories/GHSA-968p-4wvh-cqc8"},{"url":"https://github.com/babel/babel/pull/17173"},{"url":"https://github.com/babel/babel/commit/d5952e80c0faa5ec20e35085531b6e572d31dad4"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2025-27789"},{"url":"https://github.com/advisories/GHSA-968p-4wvh-cqc8"}]}}},{"dismissedAt":null,"createdAt":"2025-05-19T21:48:04Z","securityVulnerability":{"severity":"HIGH","package":{"name":"setuptools"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-5rjg-fvgr-3xxf"},{"type":"CVE","value":"CVE-2025-47273"}],"references":[{"url":"https://github.com/pypa/setuptools/security/advisories/GHSA-5rjg-fvgr-3xxf"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2025-47273"},{"url":"https://github.com/pypa/setuptools/issues/4946"},{"url":"https://github.com/pypa/setuptools/commit/250a6d17978f9f6ac3ac887091f2d32886fbbb0b"},{"url":"https://github.com/pypa/setuptools/blob/6ead555c5fb29bc57fe6105b1bffc163f56fd558/setuptools/package_index.py#L810C1-L825C88"},{"url":"https://github.com/advisories/GHSA-5rjg-fvgr-3xxf"}]}}},{"dismissedAt":null,"createdAt":"2025-05-23T19:37:14Z","securityVulnerability":{"severity":"HIGH","package":{"name":"tornado"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-7cx3-6m66-7c5m"},{"type":"CVE","value":"CVE-2025-47287"}],"references":[{"url":"https://github.com/tornadoweb/tornado/security/advisories/GHSA-7cx3-6m66-7c5m"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2025-47287"},{"url":"https://github.com/tornadoweb/tornado/commit/b39b892bf78fe8fea01dd45199aa88307e7162f3"},{"url":"https://github.com/advisories/GHSA-7cx3-6m66-7c5m"}]}}}]},"grade":"D"}]}